"""add indexes to debates creator_id created_at updated_at

Revision ID: 90593de7477b
Revises: d158e063330f
Create Date: 2026-05-14 21:48:26.346088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90593de7477b'
down_revision = 'd158e063330f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debates', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_debates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_debates_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debates_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('session_token',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('session_token',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('debates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debates_updated_at'))
        batch_op.drop_index(batch_op.f('ix_debates_creator_id'))
        batch_op.drop_index(batch_op.f('ix_debates_created_at'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
