"""add yes_upvotes no_upvotes to debates

Revision ID: bf724471673e
Revises: a1b2c3d4e5f6
Create Date: 2026-05-14 18:10:00.528932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf724471673e'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yes_upvotes', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('no_upvotes', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debates', schema=None) as batch_op:
        batch_op.drop_column('no_upvotes')
        batch_op.drop_column('yes_upvotes')

    # ### end Alembic commands ###
